/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StorefrontIndexRouteImport } from './routes/storefront/index'
import { Route as StorefrontSignupRouteImport } from './routes/storefront/signup'
import { Route as StorefrontProfileRouteImport } from './routes/storefront/profile'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StorefrontIndexRoute = StorefrontIndexRouteImport.update({
  id: '/storefront/',
  path: '/storefront/',
  getParentRoute: () => rootRouteImport,
} as any)
const StorefrontSignupRoute = StorefrontSignupRouteImport.update({
  id: '/storefront/signup',
  path: '/storefront/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StorefrontProfileRoute = StorefrontProfileRouteImport.update({
  id: '/storefront/profile',
  path: '/storefront/profile',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/storefront/profile': typeof StorefrontProfileRoute
  '/storefront/signup': typeof StorefrontSignupRoute
  '/storefront/': typeof StorefrontIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/storefront/profile': typeof StorefrontProfileRoute
  '/storefront/signup': typeof StorefrontSignupRoute
  '/storefront': typeof StorefrontIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/storefront/profile': typeof StorefrontProfileRoute
  '/storefront/signup': typeof StorefrontSignupRoute
  '/storefront/': typeof StorefrontIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/join'
    | '/login'
    | '/storefront/profile'
    | '/storefront/signup'
    | '/storefront/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/join'
    | '/login'
    | '/storefront/profile'
    | '/storefront/signup'
    | '/storefront'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/join'
    | '/login'
    | '/storefront/profile'
    | '/storefront/signup'
    | '/storefront/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  StorefrontProfileRoute: typeof StorefrontProfileRoute
  StorefrontSignupRoute: typeof StorefrontSignupRoute
  StorefrontIndexRoute: typeof StorefrontIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storefront/': {
      id: '/storefront/'
      path: '/storefront'
      fullPath: '/storefront/'
      preLoaderRoute: typeof StorefrontIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storefront/signup': {
      id: '/storefront/signup'
      path: '/storefront/signup'
      fullPath: '/storefront/signup'
      preLoaderRoute: typeof StorefrontSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storefront/profile': {
      id: '/storefront/profile'
      path: '/storefront/profile'
      fullPath: '/storefront/profile'
      preLoaderRoute: typeof StorefrontProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  StorefrontProfileRoute: StorefrontProfileRoute,
  StorefrontSignupRoute: StorefrontSignupRoute,
  StorefrontIndexRoute: StorefrontIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
